### ISSUE TITLE
CSS Recreation

### ISSUE THREAD

**Issue by cvinczefullsail** [dehp3000/dehp3000.github.io#17]
Your web page could match your inspiration closer. For example, the body text font is a sans-serif font. Yours is a serif font. This is likely caused by the validation error and the Google Font not loading properly (see validation error issue).

The header gradient should be a radial gradient. Please see https://developer.mozilla.org/en-US/docs/Web/CSS/radial-gradient()

There’s no need to use vender prefixes for gradients, all modern browsers understand them. Please see https://caniuse.com/ciu/index and https://caniuse.com/css-gradients

The background of the Faqs and footer don’t match the inspiration.

Don’t forget to add a border above the footer, like you did for the header.

Don’t use inline-block for paragraphs, they are best for things like navigation links. For example, your address paragraphs.

**Comment by dehp3000** [comment]
I believe I have addressed all of these.
