### ISSUE TITLE
CSS validation errors

### ISSUE THREAD

**Issue by cvinczefullsail** [dehp3000/dehp3000.github.io#18]
Errors caused by invalid use of @import. It can’t be inside a rule. See the Week 2 Integrative tutorial for details.

**Comment by cvinczefullsail** [comment]
Calc() function must have spaces in the formula (inside the parenthesis). For example:
	width: calc(100%/5 - 7rem); 
	
See the Week 3 Integrative tutorial for details.

**Comment by dehp3000** [comment]
Fixed.
