### ISSUE TITLE
Home page recreation

### ISSUE THREAD

**Issue by cvinczefullsail** [dehp3000/dehp3000.github.io#2]
Your home page could better match the composite. For example, the main navigation text should be uppercase and bold. 

You have borders around your Member Benefits section and Footer. 

Shop Featured Products heading should be left aligned and the text color of black. Shop should have a smaller font size. This goes for other headings on the page as well.

Product names and prices should be bold.

Missing icons in Member Benefits section, add them as background images to the articles.

Footer heading needs to be removed and other headings should be uppercase and white text color.

Missing content in the footer: copyright, guides, terms of use, etc.

**Comment by dehp3000** [comment]
fixed footer information in html section and I am working on the icons.

**Comment by cvinczefullsail** [comment]
Shop Featured Products heading should be left aligned and Shop should be a smaller font size. Cycle Club Member Benefits should be centered and Cycle Club should be smaller.
