### ISSUE TITLE
Semantic markup

### ISSUE THREAD

**Issue by cvinczefullsail** [dehp3000/dehp3000.github.io#20]
Only add ID or Class attributes if necessary. You header section ‘.noh2’ aren’t being used. Also choose Classes that have semantic meaning.

	
Avoid having ‘remove this’ headings in your HTML. Please give them semantic titles like ‘Sign in or sign up’ or remove them completely. 
	
I would recommend removing them so the page outline created by the headings will make more sense, starting with the main heading of ‘Faqs’.

**Comment by dehp3000** [comment]
Removed them however now html checkers will give warnings.
