### ISSUE TITLE
Review video questions

### ISSUE THREAD

**Issue by cvinczefullsail** [dehp3000/dehp3000.github.io#5]
Categories section: Make sure that your CSS validates. This is likely causing the issues with the headings background color. 

For the paragraphs, remove the left positioning and text align center like you did for the headings.

Use filter to make the Product images black and white. See https://css-tricks.com/almanac/properties/f/filter/

**Comment by dehp3000** [comment]
When I turn in I will have validation screenshots I fixed the errors in the video it was because I was in the middle of changing those 2 lines when I was interrupted
