### ISSUE TITLE
Reopened closed issue Layout

### ISSUE THREAD

**Issue by cvinczefullsail** [dehp3000/dehp3000.github.io#8]
The paragraphs in the Categories section still have float: none.

Don’t mix floats and positioning. For example, your Location & Details on your Contact page. Instead, float both the form  and the section, then no positioning is needed.

Use floats for any multicolumn layout, please see the textbook examples at  http://www.htmlandcssbook.com/code-samples/chapter-15/ .

Your Footer is collapsed because of floated children, make sure to clear the floats.

Instead of centering the body element, center the header, sections, footer, etc.. See the demo video Do I Need a Wrapper? in the HTML part of https://joshbloom.github.io/dws1/

_Originally posted by @cvinczefullsail in https://github.com/dehp3000/dehp3000.github.io/issues/3#issuecomment-713781843_

**Comment by dehp3000** [comment]
I don't think I know how to properly fix the centering issue without the wrapper I tried. everything else I think I fixed....
